import { Word } from "@/types/quiz";

export const INITIAL_VOCABULARY: Word[] = [
  // VOEDSEL
import { Word } from "@/types/quiz";

export const INITIAL_VOCABULARY: Word[] = [
  // --- ZINNEN & BASIS ---
  { jp: "はい", nl: "ja", romaji: "hai", categorie: "basis", taal: "hiragana", hoofdklank: "ha" },
  { jp: "いいえ", nl: "nee", romaji: "iie", categorie: "basis", taal: "hiragana", hoofdklank: "i" },
  { jp: "なまえはなんですか", nl: "wat is je naam?", romaji: "namae wa nan desu ka", categorie: "zinnen", taal: "hiragana", hoofdklank: "na" },
  { jp: "わたしは〜です", nl: "ik ben ~", romaji: "watashi wa ~ desu", categorie: "zinnen", taal: "hiragana", hoofdklank: "wa" },
  { jp: "〜からきました", nl: "ik kom uit ~", romaji: "~ kara kimashita", categorie: "zinnen", taal: "hiragana", hoofdklank: "ka" },
  { jp: "これはなんですか", nl: "wat is dit?", romaji: "kore wa nan desu ka", categorie: "zinnen", taal: "hiragana", hoofdklank: "ko" },
  { jp: "いくらですか", nl: "hoeveel kost het?", romaji: "ikura desu ka", categorie: "zinnen", taal: "hiragana", hoofdklank: "i" },
  { jp: "これください", nl: "deze graag", romaji: "kore kudasai", categorie: "zinnen", taal: "hiragana", hoofdklank: "ko" },
  { jp: "おねがいします", nl: "alstublieft", romaji: "onegaishimasu", categorie: "beleefdheid", taal: "hiragana", hoofdklank: "o" },
  { jp: "ちゅうもんおねがいします", nl: "mag ik bestellen?", romaji: "chumon onegaishimasu", categorie: "restaurant", taal: "hiragana", hoofdklank: "chu" },
  { jp: "みずをおねがいします", nl: "water alstublieft", romaji: "mizu o onegaishimasu", categorie: "restaurant", taal: "hiragana", hoofdklank: "mi" },
  { jp: "おかいけいおねがいします", nl: "de rekening alstublieft", romaji: "okaikei onegaishimasu", categorie: "restaurant", taal: "hiragana", hoofdklank: "o" },
  { jp: "ここはどこですか", nl: "waar ben ik?", romaji: "koko wa doko desu ka", categorie: "richting", taal: "hiragana", hoofdklank: "ko" },
  { jp: "トイレはどこですか", nl: "waar is het toilet?", romaji: "toire wa doko desu ka", categorie: "richting", taal: "katakana", hoofdklank: "to" },
  { jp: "えきはどこですか", nl: "waar is het station?", romaji: "eki wa doko desu ka", categorie: "richting", taal: "hiragana", hoofdklank: "e" },
  { jp: "いまなんじですか", nl: "hoe laat is het nu?", romaji: "ima nan ji desu ka", categorie: "tijd", taal: "hiragana", hoofdklank: "i" },
  { jp: "わかりません", nl: "ik begrijp het niet", romaji: "wakarimasen", categorie: "basis", taal: "hiragana", hoofdklank: "wa" },
  { jp: "にほんごをはなせません", nl: "ik spreek geen Japans", romaji: "nihongo o hanasemasen", categorie: "basis", taal: "hiragana", hoofdklank: "ni" },

  // --- GROETEN ---
  { jp: "おはようございます", nl: "goedemorgen", romaji: "ohayou gozaimasu", categorie: "groeten", taal: "hiragana", hoofdklank: "o" },
  { jp: "こんにちは", nl: "hallo / goedemiddag", romaji: "konnichiwa", categorie: "groeten", taal: "hiragana", hoofdklank: "ko" },
  { jp: "こんばんは", nl: "goedenavond", romaji: "konbanwa", categorie: "groeten", taal: "hiragana", hoofdklank: "ko" },
  { jp: "ありがとうございます", nl: "dank u wel", romaji: "arigatou gozaimasu", categorie: "groeten", taal: "hiragana", hoofdklank: "a" },
  { jp: "すみません", nl: "pardon / sorry", romaji: "sumimasen", categorie: "groeten", taal: "hiragana", hoofdklank: "su" },
  { jp: "ごめんなさい", nl: "sorry", romaji: "gomennasai", categorie: "groeten", taal: "hiragana", hoofdklank: "go" },
  { jp: "はじめまして", nl: "aangenaam kennis te maken", romaji: "hajimemashite", categorie: "groeten", taal: "hiragana", hoofdklank: "ha" },

  // --- VOEDSEL ---
  { jp: "りんご", nl: "appel", romaji: "ringo", categorie: "voedsel", taal: "hiragana", hoofdklank: "ri" },
  { jp: "みかん", nl: "sinaasappel", romaji: "mikan", categorie: "voedsel", taal: "hiragana", hoofdklank: "mi" },
  { jp: "ぶどう", nl: "druif", romaji: "budou", categorie: "voedsel", taal: "hiragana", hoofdklank: "bu" },
  { jp: "もも", nl: "perzik", romaji: "momo", categorie: "voedsel", taal: "hiragana", hoofdklank: "mo" },
  { jp: "いちご", nl: "aardbei", romaji: "ichigo", categorie: "voedsel", taal: "hiragana", hoofdklank: "i" },
  { jp: "きゅうり", nl: "komkommer", romaji: "kyuuri", categorie: "voedsel", taal: "hiragana", hoofdklank: "kyu" },
  { jp: "にんじん", nl: "wortel", romaji: "ninjin", categorie: "voedsel", taal: "hiragana", hoofdklank: "ni" },
  { jp: "じゃがいom", nl: "aardappel", romaji: "jagaimo", categorie: "voedsel", taal: "hiragana", hoofdklank: "ja" },
  { jp: "たまねぎ", nl: "ui", romaji: "tamanegi", categorie: "voedsel", taal: "hiragana", hoofdklank: "ta" },
  { jp: "にんにく", nl: "knoflook", romaji: "ninniku", categorie: "voedsel", taal: "hiragana", hoofdklank: "ni" },
  { jp: "ぎゅうにく", nl: "rundvlees", romaji: "gyuuniku", categorie: "voedsel", taal: "hiragana", hoofdklank: "gyu" },
  { jp: "ぶたにく", nl: "varkensvlees", romaji: "butaniku", categorie: "voedsel", taal: "hiragana", hoofdklank: "bu" },
  { jp: "とりにく", nl: "kippenvlees", romaji: "toriniku", categorie: "voedsel", taal: "hiragana", hoofdklank: "to" },
  { jp: "さつまいも", nl: "zoete aardappel", romaji: "satsumaimo", categorie: "voedsel", taal: "hiragana", hoofdklank: "sa" },
  { jp: "あさごはん", nl: "ontbijt", romaji: "asa-gohan", categorie: "voedsel", taal: "hiragana", hoofdklank: "a" },
  { jp: "ひるごはん", nl: "lunch", romaji: "hiru-gohan", categorie: "voedsel", taal: "hiragana", hoofdklank: "hi" },
  { jp: "よるごはん", nl: "diner", romaji: "yoru-gohan", categorie: "voedsel", taal: "hiragana", hoofdklank: "yo" },
  { jp: "たまご", nl: "ei", romaji: "tamago", categorie: "voedsel", taal: "hiragana", hoofdklank: "ta" },
  { jp: "さかな", nl: "vis", romaji: "魚", categorie: "voedsel", taal: "hiragana", hoofdklank: "sa" },
  { jp: "やさい", nl: "groente", romaji: "yasai", categorie: "voedsel", taal: "hiragana", hoofdklank: "ya" },
  { jp: "くだもの", nl: "fruit", romaji: "kudamono", categorie: "voedsel", taal: "hiragana", hoofdklank: "ku" },
  { jp: "スープ", nl: "soep", romaji: "suupu", categorie: "voedsel", taal: "katakana", hoofdklank: "su" },
  { jp: "サラダ", nl: "salade", romaji: "sarada", categorie: "voedsel", taal: "katakana", hoofdklank: "sa" },
  { jp: "パン", nl: "brood", romaji: "pan", categorie: "voedsel", taal: "katakana", hoofdklank: "pa" },
  { jp: "チーズ", nl: "kaas", romaji: "chiizu", categorie: "voedsel", taal: "katakana", hoofdklank: "chi" },
  { jp: "デザート", nl: "dessert", romaji: "dezaato", categorie: "voedsel", taal: "katakana", hoofdklank: "de" },

  // --- DRANK ---
  { jp: "みず", nl: "water", romaji: "mizu", categorie: "drank", taal: "hiragana", hoofdklank: "mi" },
  { jp: "ぎゅうにゅう", nl: "melk", romaji: "gyuunyuu", categorie: "drank", taal: "hiragana", hoofdklank: "gyu" },

  // --- MENSEN & FAMILIE ---
  { jp: "ぼく", nl: "ik (mannelijk)", romaji: "boku", categorie: "mensen", taal: "hiragana", hoofdklank: "bo" },
  { jp: "おれ", nl: "ik (informeel)", romaji: "ore", categorie: "mensen", taal: "hiragana", hoofdklank: "o" },
  { jp: "ともだち", nl: "vriend", romaji: "tomodachi", categorie: "mensen", taal: "hiragana", hoofdklank: "to" },
  { jp: "どうりょう", nl: "collega", romaji: "douryou", categorie: "mensen", taal: "hiragana", hoofdklank: "do" },
  { jp: "ぶちょう", nl: "manager", romaji: "buchou", categorie: "mensen", taal: "hiragana", hoofdklank: "bu" },
  { jp: "しゃちょう", "nl": "president/baas", romaji: "shachou", categorie: "mensen", taal: "hiragana", hoofdklank: "sha" },
  { jp: "おかあさん", nl: "moeder", romaji: "okaasan", categorie: "familie", taal: "hiragana", hoofdklank: "o" },
  { jp: "おとうさん", nl: "vader", romaji: "otousan", categorie: "familie", taal: "hiragana", hoofdklank: "o" },
  { jp: "おねえさん", nl: "oudere zus", romaji: "oneesan", categorie: "familie", taal: "hiragana", hoofdklank: "o" },
  { jp: "おにいさん", nl: "oudere broer", romaji: "oniisan", categorie: "familie", taal: "hiragana", hoofdklank: "o" },
  { jp: "いもうと", nl: "jongere zus", romaji: "imouto", categorie: "familie", taal: "hiragana", hoofdklank: "i" },
  { jp: "おとうと", nl: "jongere broer", romaji: "otouto", categorie: "familie", taal: "hiragana", hoofdklank: "o" },
  { jp: "おとな", nl: "volwassene", romaji: "otona", categorie: "mensen", taal: "hiragana", hoofdklank: "o" },
  { jp: "こども", nl: "kind", romaji: "kodomo", categorie: "mensen", taal: "hiragana", hoofdklank: "ko" },
  { jp: "かれし", nl: "vriendje", romaji: "kareshi", categorie: "mensen", taal: "hiragana", hoofdklank: "ka" },
  { jp: "かのじょ", nl: "vriendin", romaji: "kanojo", categorie: "mensen", taal: "hiragana", hoofdklank: "ka" },
  { jp: "おとこのひと", nl: "man", romaji: "otoko no hito", categorie: "mensen", taal: "hiragana", hoofdklank: "o" },
  { jp: "おんなのひと", nl: "vrouw", romaji: "onna no hito", categorie: "mensen", taal: "hiragana", hoofdklank: "o" },

  // --- LICHAAM & GEZONDHEID ---
  { jp: "けんこう", nl: "gezondheid", romaji: "kenkou", categorie: "lichaam", taal: "hiragana", hoofdklank: "ke" },
  { jp: "は", nl: "tand/gebit", romaji: "ha", categorie: "lichaam", taal: "hiragana", hoofdklank: "ha" },
  { jp: "くち", nl: "mond", romaji: "kuchi", categorie: "lichaam", taal: "hiragana", hoofdklank: "ku" },
  { jp: "のど", nl: "keel", romaji: "nodo", categorie: "lichaam", taal: "hiragana", hoofdklank: "no" },
  { jp: "せなか", nl: "rug", romaji: "senaka", categorie: "lichaam", taal: "hiragana", hoofdklank: "se" },
  { jp: "ひざ", nl: "knie", romaji: "hiza", categorie: "lichaam", taal: "hiragana", hoofdklank: "hi" },
  { jp: "かた", nl: "schouder", romaji: "kata", categorie: "lichaam", taal: "hiragana", hoofdklank: "ka" },
  { jp: "はな", nl: "neus", romaji: "hana", categorie: "lichaam", taal: "hiragana", hoofdklank: "ha" },
  { jp: "くび", nl: "nek", romaji: "kubi", categorie: "lichaam", taal: "hiragana", hoofdklank: "ku" },
  { jp: "こころ", nl: "geest/hart", romaji: "kokoro", categorie: "lichaam", taal: "hiragana", hoofdklank: "ko" },

  // --- EMOTIE ---
  { jp: "よろこび", nl: "plezier", romaji: "yorokobi", categorie: "emotie", taal: "hiragana", hoofdklank: "yo" },
  { jp: "あんしん", nl: "geruststelling", romaji: "anshin", categorie: "emotie", taal: "hiragana", hoofdklank: "a" },
  { jp: "おこる", nl: "boos", romaji: "okoru", categorie: "emotie", taal: "hiragana", hoofdklank: "o" },
  { jp: "はずかしい", nl: "verlegen", romaji: "hazukashii", categorie: "emotie", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ゆうき", nl: "moed", romaji: "yuuki", categorie: "emotie", taal: "hiragana", hoofdklank: "yu" },

  // --- NATUUR & DIEREN ---
  { jp: "やま", nl: "berg", romaji: "yama", categorie: "natuur", taal: "hiragana", hoofdklank: "ya" },
  { jp: "もり", nl: "bos", romaji: "mori", categorie: "natuur", taal: "hiragana", hoofdklank: "mo" },
  { jp: "かわ", nl: "rivier", romaji: "kawa", categorie: "natuur", taal: "hiragana", hoofdklank: "ka" },
  { jp: "うみ", nl: "zee", romaji: "umi", categorie: "natuur", taal: "hiragana", hoofdklank: "u" },
  { jp: "そら", nl: "lucht", romaji: "sora", categorie: "natuur", taal: "hiragana", hoofdklank: "so" },
  { jp: "たいよう", nl: "zon", romaji: "taiyou", categorie: "natuur", taal: "hiragana", hoofdklank: "ta" },
  { jp: "つき", nl: "maan", romaji: "tsuki", categorie: "natuur", taal: "hiragana", hoofdklank: "tsu" },
  { jp: "ほし", nl: "ster", romaji: "hoshi", categorie: "natuur", taal: "hiragana", hoofdklank: "ho" },
  { jp: "あめ", nl: "regen", romaji: "ame", categorie: "natuur", taal: "hiragana", hoofdklank: "a" },
  { jp: "ゆき", nl: "sneeuw", romaji: "yuki", categorie: "natuur", taal: "hiragana", hoofdklank: "yu" },
  { jp: "かぜ", nl: "wind", romaji: "kaze", categorie: "natuur", taal: "hiragana", hoofdklank: "ka" },
  { jp: "はな", nl: "bloem", romaji: "hana", categorie: "natuur", taal: "hiragana", hoofdklank: "ha" },
  { jp: "き", nl: "boom", romaji: "ki", categorie: "natuur", taal: "hiragana", hoofdklank: "ki" },
  { jp: "いけ", nl: "vijver", romaji: "ike", categorie: "natuur", taal: "hiragana", hoofdklank: "i" },
  { jp: "むし", nl: "insect", romaji: "mushi", categorie: "natuur", taal: "hiragana", hoofdklank: "mu" },
  { jp: "とり", nl: "vogel", romaji: "tori", categorie: "natuur", taal: "hiragana", hoofdklank: "to" },
  { jp: "さる", nl: "aap", romaji: "saru", categorie: "natuur", taal: "hiragana", hoofdklank: "sa" },
  { jp: "ねこ", nl: "kat", romaji: "neko", categorie: "natuur", taal: "hiragana", hoofdklank: "ne" },
  { jp: "いぬ", nl: "hond", romaji: "inu", categorie: "natuur", taal: "hiragana", hoofdklank: "i" },
  { jp: "うし", nl: "koe", romaji: "ushi", categorie: "natuur", taal: "hiragana", hoofdklank: "u" },
  { jp: "ぶta", nl: "varken", romaji: "buta", categorie: "natuur", taal: "hiragana", hoofdklank: "bu" },
  { jp: "うま", nl: "paard", romaji: "uma", categorie: "natuur", taal: "hiragana", hoofdklank: "u" },

  // --- SCHOOL ---
  { jp: "せんせい", nl: "leraar", romaji: "sensei", categorie: "school", taal: "hiragana", hoofdklank: "se" },
  { jp: "こうこう", nl: "high school", romaji: "kookoo", categorie: "school", taal: "hiragana", hoofdklank: "ko" },
  { jp: "じゅぎょう", nl: "les", romaji: "jugyou", categorie: "school", taal: "hiragana", hoofdklank: "ju" },
  { jp: "しけん", nl: "examen", romaji: "shiken", categorie: "school", taal: "hiragana", hoofdklank: "shi" },
  { jp: "としょかん", nl: "bibliotheek", romaji: "toshokan", categorie: "school", taal: "hiragana", hoofdklank: "to" },
  { jp: "かがく", nl: "scheikunde", romaji: "kagaku", categorie: "school", taal: "hiragana", hoofdklank: "ka" },
  { jp: "すうがく", nl: "wiskunde", romaji: "suugaku", categorie: "school", taal: "hiragana", hoofdklank: "su" },
  { jp: "にほんご", nl: "Japanse taal", romaji: "nihongo", categorie: "school", taal: "hiragana", hoofdklank: "ni" },
  { jp: "だいがく", nl: "universiteit", romaji: "daigaku", categorie: "school", taal: "hiragana", hoofdklank: "da" },
  { jp: "がくせい", nl: "student", romaji: "gakusei", categorie: "school", taal: "hiragana", hoofdklank: "ga" },
  { jp: "だいがくせい", nl: "universiteit student", romaji: "daigakusei", categorie: "school", taal: "hiragana", hoofdklank: "da" },
  { jp: "せんこう", nl: "hoofdvak (major)", romaji: "senkou", categorie: "school", taal: "hiragana", hoofdklank: "se" },

  // --- PLAATSEN ---
  { jp: "えき", nl: "station", romaji: "eki", categorie: "plaatsen", taal: "hiragana", hoofdklank: "e" },
  { jp: "びょういん", nl: "ziekenhuis", romaji: "byouin", categorie: "plaatsen", taal: "hiragana", hoofdklank: "byo" },
  { jp: "りょうがえ", nl: "wisselkantoor", romaji: "ryougae", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ryo" },
  { jp: "ぎんこう", nl: "bank", romaji: "ginkou", categorie: "plaatsen", taal: "hiragana", hoofdklank: "gi" },
  { jp: "けいさつしょ", nl: "politiebureau", romaji: "keisatsusho", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ke" },
  { jp: "こうばん", nl: "politiepost", romaji: "kouban", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ko" },
  { jp: "ゆうびんきょく", nl: "postkantoor", romaji: "yuubinkyoku", categorie: "plaatsen", taal: "hiragana", hoofdklank: "yu" },
  { jp: "コンビニ", nl: "buurtwinkel", romaji: "konbini", categorie: "plaatsen", taal: "katakana", hoofdklank: "ko" },
  { jp: "パンや", nl: "bakker", romaji: "panya", categorie: "plaatsen", taal: "hiragana", hoofdklank: "pa" },
  { jp: "みせ", nl: "winkel", romaji: "mise", categorie: "plaatsen", taal: "hiragana", hoofdklank: "mi" },
  { jp: "スーパー", nl: "supermarkt", romaji: "suupaa", categorie: "plaatsen", taal: "katakana", hoofdklank: "su" },
  { jp: "くうこう", nl: "vliegveld", romaji: "kuukou", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ku" },
  { jp: "バスてい", nl: "busstop", romaji: "basutei", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ba" },
  { jp: "みなと", nl: "haven", romaji: "minato", categorie: "plaatsen", taal: "hiragana", hoofdklank: "mi" },
  { jp: "じんじゃ", nl: "shrine", romaji: "jinja", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ji" },
  { jp: "おてら", nl: "tempel", romaji: "otera", categorie: "plaatsen", taal: "hiragana", hoofdklank: "o" },
  { jp: "まち", nl: "stad/dorp", romaji: "machi", categorie: "plaatsen", taal: "hiragana", hoofdklank: "ma" },
  { jp: "ホテル", nl: "hotel", romaji: "hoteru", categorie: "plaatsen", taal: "katakana", hoofdklank: "ho" },
  { jp: "うけつけ", nl: "receptie", romaji: "uketsuke", categorie: "plaatsen", taal: "hiragana", hoofdklank: "u" },

  // --- TRANSPORT ---
  { jp: "くるま", nl: "auto", romaji: "kuruma", categorie: "transport", taal: "hiragana", hoofdklank: "ku" },
  { jp: "じてんしゃ", nl: "fiets", romaji: "jitensha", categorie: "transport", taal: "hiragana", hoofdklank: "ji" },
  { jp: "でんしゃ", nl: "trein", romaji: "densha", categorie: "transport", taal: "hiragana", hoofdklank: "de" },
  { jp: "ひこうき", nl: "vliegtuig", romaji: "hikouki", categorie: "transport", taal: "hiragana", hoofdklank: "hi" },
  { jp: "ふね", nl: "boot", romaji: "fune", categorie: "transport", taal: "hiragana", hoofdklank: "fu" },
  { jp: "バス", nl: "bus", romaji: "basu", categorie: "transport", taal: "katakana", hoofdklank: "ba" },

  // --- KLEDING & OVERIG ---
  { jp: "くつ", nl: "schoenen", romaji: "kutsu", categorie: "kleding", taal: "hiragana", hoofdklank: "ku" },
  { jp: "ふく", nl: "kleding", romaji: "fuku", categorie: "kleding", taal: "hiragana", hoofdklank: "fu" },
  { jp: "ぼうし", nl: "hoed", romaji: "boushi", categorie: "kleding", taal: "hiragana", hoofdklank: "bo" },
  { jp: "てぶくろ", nl: "handschoenen", romaji: "tebukuro", categorie: "kleding", taal: "hiragana", hoofdklank: "te" },
  { jp: "マフラー", nl: "sjaal", romaji: "mafuraa", categorie: "kleding", taal: "katakana", hoofdklank: "ma" },
  { jp: "スカート", nl: "rok", romaji: "sukaato", categorie: "kleding", taal: "katakana", hoofdklank: "su" },
  { jp: "シャツ", nl: "shirt", romaji: "shatsu", categorie: "kleding", taal: "katakana", hoofdklank: "sha" },
  { jp: "ズボン", nl: "broek", romaji: "zubon", categorie: "kleding", taal: "katakana", hoofdklank: "zu" },
  { jp: "ワンピース", nl: "jurk", romaji: "wanpiisu", categorie: "kleding", taal: "katakana", hoofdklank: "wa" },
  { jp: "くびわ", nl: "ketting", romaji: "kubiwa", categorie: "kleding", taal: "hiragana", hoofdklank: "ku" },
  { jp: "かさ", nl: "paraplu", romaji: "kasa", categorie: "overig", taal: "hiragana", hoofdklank: "ka" },
  { jp: "めがね", nl: "bril", romaji: "megane", categorie: "overig", taal: "hiragana", hoofdklank: "me" },
  { jp: "けいたい", nl: "telefoon", romaji: "keitai", categorie: "overig", taal: "hiragana", hoofdklank: "ke" },
  { jp: "でんき", nl: "licht", romaji: "denki", categorie: "overig", taal: "hiragana", hoofdklank: "de" },
  { jp: "がっき", nl: "instrument", romaji: "gakki", categorie: "overig", taal: "hiragana", hoofdklank: "ga" },
  { jp: "ピアノ", nl: "piano", romaji: "piano", categorie: "overig", taal: "katakana", hoofdklank: "pi" },
  { jp: "バイオリン", nl: "viool", romaji: "baiorin", categorie: "overig", taal: "katakana", hoofdklank: "ba" },

  // --- SPORT ---
  { jp: "サッカー", nl: "voetbal", romaji: "sakkaa", categorie: "sport", taal: "katakana", hoofdklank: "sa" },
  { jp: "やきゅう", nl: "honkbal", romaji: "yakyuu", categorie: "sport", taal: "hiragana", hoofdklank: "ya" },
  { jp: "バスケット", nl: "basketbal", romaji: "basuketto", categorie: "sport", taal: "katakana", hoofdklank: "ba" },
  { jp: "すいえい", nl: "zwemmen", romaji: "suiei", categorie: "sport", taal: "hiragana", hoofdklank: "su" },
  { jp: "テニス", nl: "tennis", romaji: "tenisu", categorie: "sport", taal: "katakana", hoofdklank: "te" },
  { jp: "ジョギング", nl: "joggen", romaji: "jogingu", categorie: "sport", taal: "katakana", hoofdklank: "jo" },
  { jp: "ランニング", nl: "hardlopen", romaji: "ranningu", categorie: "sport", taal: "katakana", hoofdklank: "ra" },

  // --- KLEUREN ---
  { jp: "あか", nl: "rood", romaji: "aka", categorie: "kleuren", taal: "hiragana", hoofdklank: "a" },
  { jp: "あお", nl: "blauw", romaji: "ao", categorie: "kleuren", taal: "hiragana", hoofdklank: "a" },
  { jp: "きいろ", nl: "geel", romaji: "kiiro", categorie: "kleuren", taal: "hiragana", hoofdklank: "ki" },
  { jp: "みどり", nl: "groen", romaji: "midori", categorie: "kleuren", taal: "hiragana", hoofdklank: "mi" },
  { jp: "しろ", nl: "wit", romaji: "shiro", categorie: "kleuren", taal: "hiragana", hoofdklank: "shi" },
  { jp: "くろ", nl: "zwart", romaji: "kuro", categorie: "kleuren", taal: "hiragana", hoofdklank: "ku" },
  { jp: "むらさき", nl: "paars", romaji: "murasaki", categorie: "kleuren", taal: "hiragana", hoofdklank: "mu" },
  { jp: "オレンジ", nl: "oranje", romaji: "orenji", categorie: "kleuren", taal: "katakana", hoofdklank: "o" },
  { jp: "ピンク", nl: "roze", romaji: "pinku", categorie: "kleuren", taal: "katakana", hoofdklank: "pi" },
  { jp: "ちゃいろ", nl: "bruin", romaji: "chairo", categorie: "kleuren", taal: "hiragana", hoofdklank: "cha" },

  // --- WERKWOORDEN ---
  { jp: "たべる", nl: "eten", romaji: "taberu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ta" },
  { jp: "いく", nl: "gaan", romaji: "iku", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "i" },
  { jp: "のむ", nl: "drinken", romaji: "nomu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "no" },
  { jp: "きく", nl: "luisteren/vragen", romaji: "kiku", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ki" },
  { jp: "よむ", nl: "lezen", romaji: "yomu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "yo" },
  { jp: "みる", nl: "kijken", romaji: "miru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "mi" },
  { jp: "ねる", nl: "slapen", romaji: "neru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ne" },
  { jp: "おきる", nl: "opstaan", romaji: "okiru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "o" },
  { jp: "はなす", nl: "praten/spreken", romaji: "hanasu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ha" },
  { jp: "かえる", nl: "teruggaan", romaji: "kaeru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ka" },
  { jp: "すわる", nl: "zitten", romaji: "suwaru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "su" },
  { jp: "たつ", nl: "staan", romaji: "tatsu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ta" },
  { jp: "およぐ", nl: "zwemmen", romaji: "oyogu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "o" },
  { jp: "あそぶ", nl: "spelen", romaji: "asobu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "a" },
  { jp: "のる", nl: "rijden/instappen", romaji: "noru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "no" },
  { jp: "かう", nl: "kopen", romaji: "kau", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ka" },
  { jp: "あう", nl: "ontmoeten", romaji: "au", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "a" },
  { jp: "かく", nl: "schrijven", romaji: "kaku", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ka" },
  { jp: "まつ", nl: "wachten", romaji: "matsu", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "ma" },
  { jp: "とる", nl: "foto maken", romaji: "toru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "to" },
  { jp: "する", nl: "doen", romaji: "suru", categorie: "werkwoorden", taal: "hiragana", hoofdklank: "su" },

  // --- TIJD, DAGEN & MAANDEN ---
  { jp: "きょう", nl: "vandaag", romaji: "kyou", categorie: "tijd", taal: "hiragana", hoofdklank: "kyo" },
  { jp: "きのう", nl: "gisteren", romaji: "kinou", categorie: "tijd", taal: "hiragana", hoofdklank: "ki" },
  { jp: "あした", nl: "morgen", romaji: "ashita", categorie: "tijd", taal: "hiragana", hoofdklank: "a" },
  { jp: "こんしゅう", nl: "deze week", romaji: "konshuu", categorie: "tijd", taal: "hiragana", hoofdklank: "ko" },
  { jp: "せんしゅう", nl: "vorige week", romaji: "senshuu", categorie: "tijd", taal: "hiragana", hoofdklank: "se" },
  { jp: "らいしゅう", nl: "volgende week", romaji: "raishuu", categorie: "tijd", taal: "hiragana", hoofdklank: "ra" },
  { jp: "こんげつ", nl: "deze maand", romaji: "kongetsu", categorie: "tijd", taal: "hiragana", hoofdklank: "ko" },
  { jp: "せんげつ", nl: "vorige maand", romaji: "sengetsu", categorie: "tijd", taal: "hiragana", hoofdklank: "se" },
  { jp: "らいげつ", nl: "volgende maand", romaji: "raigetsu", categorie: "tijd", taal: "hiragana", hoofdklank: "ra" },
  { jp: "ことし", nl: "dit jaar", romaji: "kotoshi", categorie: "tijd", taal: "hiragana", hoofdklank: "ko" },
  { jp: "きょねん", nl: "vorig jaar", romaji: "kyonen", categorie: "tijd", taal: "hiragana", hoofdklank: "kyo" },
  { jp: "らいねん", nl: "volgend jaar", romaji: "rainen", categorie: "tijd", taal: "hiragana", hoofdklank: "ra" },
  { jp: "げつようび", nl: "maandag", romaji: "getsuyoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "ge" },
  { jp: "かようび", nl: "dinsdag", romaji: "kayoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "ka" },
  { jp: "すいようび", nl: "woensdag", romaji: "suiyoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "su" },
  { jp: "もくようび", nl: "donderdag", romaji: "mokuyoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "mo" },
  { jp: "きんようび", nl: "vrijdag", romaji: "kinyoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "ki" },
  { jp: "どようび", nl: "zaterdag", romaji: "doyoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "do" },
  { jp: "にちようび", nl: "zondag", romaji: "nichiyoubi", categorie: "dagen", taal: "hiragana", hoofdklank: "ni" },
  { jp: "いちがつ", nl: "januari", romaji: "ichigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "i" },
  { jp: "にがつ", nl: "februari", romaji: "nigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "ni" },
  { jp: "さんがつ", nl: "maart", romaji: "sangatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "sa" },
  { jp: "しがつ", nl: "april", romaji: "shigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "shi" },
  { jp: "ごがつ", nl: "mei", romaji: "gogatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "go" },
  { jp: "ろくがつ", nl: "juni", romaji: "rokugatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "ro" },
  { jp: "しちがつ", nl: "juli", romaji: "shichigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "shi" },
  { jp: "はちがつ", nl: "augustus", romaji: "hachigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "ha" },
  { jp: "くがつ", nl: "september", romaji: "kugatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "ku" },
  { jp: "じゅうがつ", nl: "oktober", romaji: "juugatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "juu" },
  { jp: "じゅういちがつ", nl: "november", romaji: "juuichigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "juu" },
  { jp: "じゅうにがつ", nl: "december", romaji: "juunigatsu", categorie: "maanden", taal: "hiragana", hoofdklank: "juu" },

  // --- GETALLEN (Uren/Basis) ---
  { jp: "いち", nl: "1", romaji: "ichi", categorie: "getallen", taal: "hiragana", hoofdklank: "i" },
  { jp: "に", nl: "2", romaji: "ni", categorie: "getallen", taal: "hiragana", hoofdklank: "ni" },
  { jp: "さん", nl: "3", romaji: "san", categorie: "getallen", taal: "hiragana", hoofdklank: "sa" },
  { jp: "よん", nl: "4", romaji: "yon", categorie: "getallen", taal: "hiragana", hoofdklank: "yo" },
  { jp: "ご", nl: "5", romaji: "go", categorie: "getallen", taal: "hiragana", hoofdklank: "go" },
  { jp: "ろく", nl: "6", romaji: "roku", categorie: "getallen", taal: "hiragana", hoofdklank: "ro" },
  { jp: "なな", nl: "7", romaji: "nana", categorie: "getallen", taal: "hiragana", hoofdklank: "na" },
  { jp: "はち", nl: "8", romaji: "hachi", categorie: "getallen", taal: "hiragana", hoofdklank: "ha" },
  { jp: "きゅう", nl: "9", romaji: "kyuu", categorie: "getallen", taal: "hiragana", hoofdklank: "kyu" },
  { jp: "じゅう", nl: "10", romaji: "juu", categorie: "getallen", taal: "hiragana", hoofdklank: "ju" },

  // --- HIRAGANA ALFABET ---
  { jp: "あ", nl: "a", romaji: "a", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "a" },
  { jp: "い", nl: "i", romaji: "i", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "a" },
  { jp: "う", nl: "u", romaji: "u", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "a" },
  { jp: "え", nl: "e", romaji: "e", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "a" },
  { jp: "お", nl: "o", romaji: "o", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "a" },
  { jp: "か", nl: "ka", romaji: "ka", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "き", nl: "ki", romaji: "ki", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "く", nl: "ku", romaji: "ku", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "け", nl: "ke", romaji: "ke", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "こ", nl: "ko", romaji: "ko", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "さ", nl: "sa", romaji: "sa", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "し", nl: "shi", romaji: "shi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "す", nl: "su", romaji: "su", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "せ", nl: "se", romaji: "se", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "そ", nl: "so", romaji: "so", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "た", nl: "ta", romaji: "ta", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "ち", nl: "chi", romaji: "chi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "つ", nl: "tsu", romaji: "tsu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "て", nl: "te", romaji: "te", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "と", nl: "to", romaji: "to", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "な", nl: "na", romaji: "na", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "na" },
  { jp: "に", nl: "ni", romaji: "ni", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "na" },
  { jp: "ぬ", nl: "nu", romaji: "nu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "na" },
  { jp: "ね", nl: "ne", romaji: "ne", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "na" },
  { jp: "の", nl: "no", romaji: "no", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "na" },
  { jp: "は", nl: "ha", romaji: "ha", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ひ", nl: "hi", romaji: "hi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ふ", nl: "fu", romaji: "fu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "へ", nl: "he", romaji: "he", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ほ", nl: "ho", romaji: "ho", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ま", nl: "ma", romaji: "ma", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ma" },
  { jp: "み", nl: "mi", romaji: "mi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ma" },
  { jp: "む", nl: "mu", romaji: "mu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ma" },
  { jp: "め", nl: "me", romaji: "me", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ma" },
  { jp: "も", nl: "mo", romaji: "mo", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ma" },
  { jp: "や", nl: "ya", romaji: "ya", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ya" },
  { jp: "ゆ", nl: "yu", romaji: "yu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ya" },
  { jp: "よ", nl: "yo", romaji: "yo", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ya" },
  { jp: "ら", nl: "ra", romaji: "ra", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ra" },
  { jp: "り", nl: "ri", romaji: "ri", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ra" },
  { jp: "る", nl: "ru", romaji: "ru", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ra" },
  { jp: "れ", nl: "re", romaji: "re", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ra" },
  { jp: "ろ", nl: "ro", romaji: "ro", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ra" },
  { jp: "わ", nl: "wa", romaji: "wa", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "wa" },
  { jp: "を", nl: "wo", romaji: "wo", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "wa" },
  { jp: "ん", nl: "n", romaji: "n", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "wa" },

  // --- KATAKANA ALFABET ---
  { jp: "ア", nl: "a", romaji: "a", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "a" },
  { jp: "イ", nl: "i", romaji: "i", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "a" },
  { jp: "ウ", nl: "u", romaji: "u", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "a" },
  { jp: "エ", nl: "e", romaji: "e", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "a" },
  { jp: "オ", nl: "o", romaji: "o", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "a" },
  { jp: "カ", nl: "ka", romaji: "ka", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "キ", nl: "ki", romaji: "ki", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "ク", nl: "ku", romaji: "ku", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "ケ", nl: "ke", romaji: "ke", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "コ", nl: "ko", romaji: "ko", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "サ", nl: "sa", romaji: "sa", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "シ", nl: "shi", romaji: "shi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ス", nl: "su", romaji: "su", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "セ", nl: "se", romaji: "se", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ソ", nl: "so", romaji: "so", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "タ", nl: "ta", romaji: "ta", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "チ", nl: "chi", romaji: "chi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "ツ", nl: "tsu", romaji: "tsu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "テ", nl: "te", romaji: "te", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "ト", nl: "to", romaji: "to", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "ナ", nl: "na", romaji: "na", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "na" },
  { jp: "ニ", nl: "ni", romaji: "ni", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "na" },
  { jp: "ヌ", nl: "nu", romaji: "nu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "na" },
  { jp: "ネ", nl: "ne", romaji: "ne", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "na" },
  { jp: "ノ", nl: "no", romaji: "no", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "na" },
  { jp: "ハ", nl: "ha", romaji: "ha", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ヒ", nl: "hi", romaji: "hi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "フ", nl: "fu", romaji: "fu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ヘ", nl: "he", romaji: "he", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ホ", nl: "ho", romaji: "ho", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "マ", nl: "ma", romaji: "ma", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ma" },
  { jp: "ミ", nl: "mi", romaji: "mi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ma" },
  { jp: "ム", nl: "mu", romaji: "mu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ma" },
  { jp: "メ", nl: "me", romaji: "me", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ma" },
  { jp: "モ", nl: "mo", romaji: "mo", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ma" },
  { jp: "ヤ", nl: "ya", romaji: "ya", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ya" },
  { jp: "ユ", nl: "yu", romaji: "yu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ya" },
  { jp: "ヨ", nl: "yo", romaji: "yo", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ya" },
  { jp: "ラ", nl: "ra", romaji: "ra", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ra" },
  { jp: "リ", nl: "ri", romaji: "ri", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ra" },
  { jp: "ル", nl: "ru", romaji: "ru", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ra" },
  { jp: "レ", nl: "re", romaji: "re", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ra" },
  { jp: "ロ", nl: "ro", romaji: "ro", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ra" },
  { jp: "ワ", nl: "wa", romaji: "wa", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "wa" },
  { jp: "ヲ", nl: "wo", romaji: "wo", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "wa" },
  { jp: "ン", nl: "n", romaji: "n", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "wa" },

  // --- DAKUTEN HIRAGANA ---
  { jp: "が", nl: "ga", romaji: "ga", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "ぎ", nl: "gi", romaji: "gi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "ぐ", nl: "gu", romaji: "gu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "げ", nl: "ge", romaji: "ge", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "ご", nl: "go", romaji: "go", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ka" },
  { jp: "ざ", nl: "za", romaji: "za", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "じ", nl: "ji", romaji: "ji", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "ず", nl: "zu", romaji: "zu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "ぜ", nl: "ze", romaji: "ze", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "ぞ", nl: "zo", romaji: "zo", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "sa" },
  { jp: "だ", nl: "da", romaji: "da", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "ぢ", nl: "ji", romaji: "ji", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "づ", nl: "zu", romaji: "zu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "で", nl: "de", romaji: "de", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "ど", nl: "do", romaji: "do", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ta" },
  { jp: "ば", nl: "ba", romaji: "ba", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "び", nl: "bi", romaji: "bi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぶ", nl: "bu", romaji: "bu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "べ", nl: "be", romaji: "be", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぼ", nl: "bo", romaji: "bo", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぱ", nl: "pa", romaji: "pa", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぴ", nl: "pi", romaji: "pi", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぷ", nl: "pu", romaji: "pu", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぺ", nl: "pe", romaji: "pe", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },
  { jp: "ぽ", nl: "po", romaji: "po", categorie: "hiragana alfabet", taal: "hiragana", hoofdklank: "ha" },

  // --- DAKUTEN KATAKANA ---
  { jp: "ガ", nl: "ga", romaji: "ga", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "ギ", nl: "gi", romaji: "gi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "グ", nl: "gu", romaji: "gu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "ゲ", nl: "ge", romaji: "ge", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "ゴ", nl: "go", romaji: "go", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ka" },
  { jp: "ザ", nl: "za", romaji: "za", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ジ", nl: "ji", romaji: "ji", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ズ", nl: "zu", romaji: "zu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ゼ", nl: "ze", romaji: "ze", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ゾ", nl: "zo", romaji: "zo", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "sa" },
  { jp: "ダ", nl: "da", romaji: "da", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "ヂ", nl: "ji", romaji: "ji", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "ヅ", nl: "zu", romaji: "zu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "デ", nl: "de", romaji: "de", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "ド", nl: "do", romaji: "do", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ta" },
  { jp: "バ", nl: "ba", romaji: "ba", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ビ", nl: "bi", romaji: "bi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ブ", nl: "bu", romaji: "bu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ベ", nl: "be", romaji: "be", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ボ", nl: "bo", romaji: "bo", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "パ", nl: "pa", romaji: "pa", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ピ", nl: "pi", romaji: "pi", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "プ", nl: "pu", romaji: "pu", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ペ", nl: "pe", romaji: "pe", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" },
  { jp: "ポ", nl: "po", romaji: "po", categorie: "katakana alfabet", taal: "katakana", hoofdklank: "ha" }
];

export const CATEGORIES = [
  "drinken", "voedsel", "lichaam", "literatuur", "emotie", 
  "school", "cultuur", "natuur", "transport", "kleding", 
  "sport", "groeten", "familie", "tijd", "katakana alfabet", 
  "hiragana alfabet", "overig"
];

export const KANA_ROWS = ["a", "ka", "sa", "ta", "na", "ma", "ha", "wa", "ra", "ya"];
