import { Word } from "@/types/quiz";

export const INITIAL_VOCABULARY: Word[] = [
  // VOEDSEL
  {jp:"りんご",nl:"appel",romaji:"ringo",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"みかん",nl:"sinaasappel",romaji:"mikan",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"ぶどう",nl:"druif",romaji:"budou",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"もも",nl:"perzik",romaji:"momo",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"いちご",nl:"aardbei",romaji:"ichigo",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"きゅうり",nl:"komkommer",romaji:"kyuuri",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"にんじん",nl:"wortel",romaji:"ninjin",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"じゃがいも",nl:"aardappel",romaji:"jagaimo",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"たまねぎ",nl:"ui",romaji:"tamanegi",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"にんにく",nl:"knoflook",romaji:"ninniku",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"ぎゅうにく",nl:"rundvlees",romaji:"gyuuniku",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"ぶたにく",nl:"varkensvlees",romaji:"butaniku",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"とりにく",nl:"kippenvlees",romaji:"toriniku",categorie:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"さつまいom",nl:"zoete aardappel",romaji:"satsumaimo",categorie:"voedsel",taal:"hiragana",hoofdklank:""},

  // FAMILIE
  {jp:"おかあさん",nl:"moeder",romaji:"okaasan",categorie:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おとうさん",nl:"vader",romaji:"otoosan",categorie:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おねえさん",nl:"oudere zus",romaji:"oneesan",categorie:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おにいさん",nl:"oudere broer",romaji:"oniisan",categorie:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"いもうと",nl:"jonger zusje",romaji:"imooto",categorie:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おとうと",nl:"jonger broertje",romaji:"otooto",categorie:"familie",taal:"hiragana",hoofdklank:""},

  // LICHAAM
  {jp:"けんこう",nl:"gezondheid",romaji:"kenkou",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"は",nl:"gebit",romaji:"ha",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"くち",nl:"mond",romaji:"kuchi",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"のど",nl:"keel",romaji:"nodo",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"せなか",nl:"rug",romaji:"senaka",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"ひざ",nl:"knie",romaji:"hiza",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"かた",nl:"schouder",romaji:"kata",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"はな",nl:"neus",romaji:"hana",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"くび",nl:"nek",romaji:"kubi",categorie:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"こころ",nl:"geest",romaji:"kokoro",categorie:"lichaam",taal:"hiragana",hoofdklank:""},

  // EMOTIE
  {jp:"よろこび",nl:"plezier",romaji:"yorokobi",categorie:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"あんしん",nl:"gerust",romaji:"anshin",categorie:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"おこる",nl:"boos",romaji:"okoru",categorie:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"はずかしい",nl:"verlegen",romaji:"hazukashii",categorie:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"ゆうki",nl:"moed",romaji:"yuuki",categorie:"emotie",taal:"hiragana",hoofdklank:""},

  // CULTUUR
  {jp:"ともだち",nl:"vriend",romaji:"tomodachi",categorie:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"かぞく",nl:"gezin",romaji:"kazoku",categorie:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"じんじゃ",nl:"shrine",romaji:"jinja",categorie:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"おてら",nl:"temple",romaji:"otera",categorie:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"ぶんか",nl:"cultuur",romaji:"bunka",categorie:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"えいが",nl:"film",romaji:"eiga",categorie:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"うつくしい",nl:"schoon",romaji:"utsukushii",categorie:"cultuur",taal:"hiragana",hoofdklank:""},

  // SCHOOL
  {jp:"せんせい",nl:"leraar",romaji:"sensei",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"こうこう",nl:"high school",romaji:"kookoo",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"じゅぎょう",nl:"les",romaji:"jugyou",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"しけん",nl:"examen",romaji:"shiken",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"としょかん",nl:"bibliotheek",romaji:"toshokan",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"かがく",nl:"scheikunde",romaji:"kagaku",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"すうがく",nl:"wiskunde",romaji:"suugaku",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"にほんご",nl:"Japanse taal",romaji:"nihongo",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"다いがく",nl:"universiteit",romaji:"daigaku",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"がくせい",nl:"student",romaji:"gakusee",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"だいがくせい",nl:"universiteits student",romaji:"daigakusee",categorie:"school",taal:"hiragana",hoofdklank:""},
  {jp:"せんこう",nl:"master",romaji:"senkoo",categorie:"school",taal:"hiragana",hoofdklank:""},

  // NATUUR
  {jp:"やま",nl:"berg",romaji:"yama",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"もり",nl:"bos",romaji:"mori",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"かわ",nl:"rivier",romaji:"kawa",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"うみ",nl:"zee",romaji:"umi",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"そら",nl:"lucht",romaji:"sora",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"たいよう",nl:"zon",romaji:"taiyou",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"つき",nl:"maan",romaji:"tsuki",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"ほし",nl:"ster",romaji:"hoshi",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"あめ",nl:"regen",romaji:"ame",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"ゆき",nl:"sneeuw",romaji:"yuki",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"かぜ",nl:"wind",romaji:"kaze",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"はな",nl:"flower",romaji:"hana",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"き",nl:"boom",romaji:"ki",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"いけ",nl:"vijver",romaji:"ike",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"むし",nl:"insect",romaji:"mushi",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"とり",nl:"vogel",romaji:"tori",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"さる",nl:"aap",romaji:"saru",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"うし",nl:"koe",romaji:"ushi",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"ねこ",nl:"kat",romaji:"neko",categorie:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"いぬ",nl:"hond",romaji:"inu",categorie:"natuur",taal:"hiragana",hoofdklank:""},

  // TRANSPORT
  {jp:"クルマ",nl:"auto",romaji:"kuruma",categorie:"transport",taal:"katakana",hoofdklank:""},
  {jp:"じてんしゃ",nl:"fiets",romaji:"jitensha",categorie:"transport",taal:"hiragana",hoofdklank:""},
  {jp:"でんしゃ",nl:"trein",romaji:"densha",categorie:"transport",taal:"hiragana",hoofdklank:""},
  {jp:"ヒコウキ",nl:"vliegtuig",romaji:"hikouki",categorie:"transport",taal:"katakana",hoofdklank:""},
  {jp:"ふね",nl:"boot",romaji:"fune",categorie:"transport",taal:"hiragana",hoofdklank:""},
  {jp:"バス",nl:"bus",romaji:"basu",categorie:"transport",taal:"katakana",hoofdklank:""},

  // KLEDING
  {jp:"くつ",nl:"schoenen",romaji:"kutsu",categorie:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"ふく",nl:"kleding",romaji:"fuku",categorie:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"ぼうし",nl:"hoed",romaji:"boushi",categorie:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"てぶくろ",nl:"handschoenen",romaji:"tebukuro",categorie:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"マフラー",nl:"sjaal",romaji:"mafuraa",categorie:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"スカート",nl:"rok",romaji:"sukaato",categorie:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"シャツ",nl:"shirt",romaji:"shatsu",categorie:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"ズボン",nl:"broek",romaji:"zubon",categorie:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"ワンピース",nl:"jurk",romaji:"wanpiisu",categorie:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"くびわ",nl:"ketting",romaji:"kubiwa",categorie:"kleding",taal:"hiragana",hoofdklank:""},

  // OVERIG
  {jp:"かさ",nl:"paraplu",romaji:"kasa",categorie:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"めがね",nl:"bril",romaji:"megane",categorie:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"けいたい",nl:"telefoon",romaji:"keitai",categorie:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"でんき",nl:"licht",romaji:"denki",categorie:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"がっき",nl:"muziekinstrument",romaji:"gakki",categorie:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"ピアノ",nl:"piano",romaji:"piano",categorie:"overig",taal:"katakana",hoofdklank:""},
  {jp:"バイオリン",nl:"viool",romaji:"baiorin",categorie:"overig",taal:"katakana",hoofdklank:""},

  // SPORT
  {jp:"サッカー",nl:"voetbal",romaji:"sakkaa",categorie:"sport",taal:"katakana",hoofdklank:""},
  {jp:"やきゅう",nl:"honkbal",romaji:"yakyuu",categorie:"sport",taal:"hiragana",hoofdklank:""},
  {jp:"バスケット",nl:"basketbal",romaji:"basuketto",categorie:"sport",taal:"katakana",hoofdklank:""},
  {jp:"すいえい",nl:"zwemmen",romaji:"sui-ei",categorie:"sport",taal:"hiragana",hoofdklank:""},
  {jp:"テニス",nl:"tennis",romaji:"tenisu",categorie:"sport",taal:"katakana",hoofdklank:""},
  {jp:"ジョギング",nl:"joggen",romaji:"jogingu",categorie:"sport",taal:"katakana",hoofdklank:""},
  {jp:"ランニング",nl:"running",romaji:"ranningu",categorie:"sport",taal:"katakana",hoofdklank:""},

  // LITERATUUR
  {jp:"え",nl:"tekening",romaji:"e",categorie:"literatuur",taal:"hiragana",hoofdklank:""},

  // GROETEN
  {jp:"ありがとうございます",nl:"dankuwel",romaji:"arigatou gozaimasu",categorie:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"こんにちは",nl:"hallo",romaji:"konnichiwa",categorie:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"おはようございます",nl:"goedemorgen",romaji:"ohayou gozaimasu",categorie:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"すみません",nl:"pardon",romaji:"sumimasen",categorie:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"ごめんなさい",nl:"sorry",romaji:"gomennasai",categorie:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"はい",nl:"ja",romaji:"hai",categorie:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"はじめまして",nl:"leuk om je te ontmoeten",romaji:"hajimemashite",categorie:"groeten",taal:"hiragana",hoofdklank:""},

  // TIJD
  {jp:"きょう",nl:"vandaag",romaji:"kyou",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"きのう",nl:"gisteren",romaji:"kinou",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"あした",nl:"morgen",romaji:"ashita",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"しゅう",nl:"week",romaji:"shuu",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"とし",nl:"jaar",romaji:"toshi",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"びょう",nl:"seconde",romaji:"byou",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"いま",nl:"nu",romaji:"ima",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"ごぜん",nl:"00.00-12.00",romaji:"gozen",categorie:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"ごご",nl:"12.00-00.00",romaji:"gogo",categorie:"tijd",taal:"hiragana",hoofdklank:""},

  // HIRAGANA ALFABET
  {jp:"あ",nl:"a",romaji:"a",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"い",nl:"i",romaji:"i",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"う",nl:"u",romaji:"u",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"え",nl:"e",romaji:"e",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"お",nl:"o",romaji:"o",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"か",nl:"ka",romaji:"ka",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"き",nl:"ki",romaji:"ki",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"く",nl:"ku",romaji:"ku",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"け",nl:"ke",romaji:"ke",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"こ",nl:"ko",romaji:"ko",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"さ",nl:"sa",romaji:"sa",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"し",nl:"shi",romaji:"shi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"す",nl:"su",romaji:"su",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"せ",nl:"se",romaji:"se",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"そ",nl:"so",romaji:"so",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"た",nl:"ta",romaji:"ta",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ち",nl:"chi",romaji:"chi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"つ",nl:"tsu",romaji:"tsu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"て",nl:"te",romaji:"te",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"と",nl:"to",romaji:"to",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"な",nl:"na",romaji:"na",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"に",nl:"ni",romaji:"ni",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"ぬ",nl:"nu",romaji:"nu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"ね",nl:"ne",romaji:"ne",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"の",nl:"no",romaji:"no",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"は",nl:"ha",romaji:"ha",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ひ",nl:"hi",romaji:"hi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ふ",nl:"fu",romaji:"fu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"へ",nl:"he",romaji:"he",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ほ",nl:"ho",romaji:"ho",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ま",nl:"ma",romaji:"ma",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"み",nl:"mi",romaji:"mi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"む",nl:"mu",romaji:"mu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"め",nl:"me",romaji:"me",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"も",nl:"mo",romaji:"mo",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"や",nl:"ya",romaji:"ya",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ya"},
  {jp:"ゆ",nl:"yu",romaji:"yu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ya"},
  {jp:"よ",nl:"yo",romaji:"yo",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ya"},
  {jp:"ら",nl:"ra",romaji:"ra",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"り",nl:"ri",romaji:"ri",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"る",nl:"ru",romaji:"ru",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"れ",nl:"re",romaji:"re",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"ろ",nl:"ro",romaji:"ro",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"わ",nl:"wa",romaji:"wa",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"wa"},
  {jp:"を",nl:"wo",romaji:"wo",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"wa"},
  {jp:"ん",nl:"n",romaji:"n",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"wa"},

  // KATAKANA ALFABET
  {jp:"ア",nl:"a",romaji:"a",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"イ",nl:"i",romaji:"i",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"ウ",nl:"u",romaji:"u",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"エ",nl:"e",romaji:"e",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"オ",nl:"o",romaji:"o",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"カ",nl:"ka",romaji:"ka",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"キ",nl:"ki",romaji:"ki",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ク",nl:"ku",romaji:"ku",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ケ",nl:"ke",romaji:"ke",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"コ",nl:"ko",romaji:"ko",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"サ",nl:"sa",romaji:"sa",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"シ",nl:"shi",romaji:"shi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ス",nl:"su",romaji:"su",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"セ",nl:"se",romaji:"se",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ソ",nl:"so",romaji:"so",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"タ",nl:"ta",romaji:"ta",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"チ",nl:"chi",romaji:"chi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ツ",nl:"tsu",romaji:"tsu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"テ",nl:"te",romaji:"te",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ト",nl:"to",romaji:"to",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ナ",nl:"na",romaji:"na",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ニ",nl:"ni",romaji:"ni",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ヌ",nl:"nu",romaji:"nu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ネ",nl:"ne",romaji:"ne",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ノ",nl:"no",romaji:"no",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ハ",nl:"ha",romaji:"ha",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ヒ",nl:"hi",romaji:"hi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"フ",nl:"fu",romaji:"fu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"へ",nl:"he",romaji:"he",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ホ",nl:"ho",romaji:"ho",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"マ",nl:"ma",romaji:"ma",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"ミ",nl:"mi",romaji:"mi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"ム",nl:"mu",romaji:"mu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"メ",nl:"me",romaji:"me",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"モ",nl:"mo",romaji:"mo",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"ヤ",nl:"ya",romaji:"ya",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ya"},
  {jp:"ユ",nl:"yu",romaji:"yu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ya"},
  {jp:"ヨ",nl:"yo",romaji:"yo",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ya"},
  {jp:"ラ",nl:"ra",romaji:"ra",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"リ",nl:"ri",romaji:"ri",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"ル",nl:"ru",romaji:"ru",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"レ",nl:"re",romaji:"re",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"ロ",nl:"ro",romaji:"ro",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"ワ",nl:"wa",romaji:"wa",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"wa"},
  {jp:"ヲ",nl:"wo",romaji:"wo",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"wa"},
  {jp:"ン",nl:"n",romaji:"n",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"wa"},

  // DAKUTEN HIRAGANA
  {jp:"が",nl:"ga",romaji:"ga",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ぎ",nl:"gi",romaji:"gi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ぐ",nl:"gu",romaji:"gu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"げ",nl:"ge",romaji:"ge",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ご",nl:"go",romaji:"go",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ざ",nl:"za",romaji:"za",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"じ",nl:"ji",romaji:"ji",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"ず",nl:"zu",romaji:"zu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"ぜ",nl:"ze",romaji:"ze",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"ぞ",nl:"zo",romaji:"zo",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"だ",nl:"da",romaji:"da",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ぢ",nl:"ji",romaji:"ji",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"づ",nl:"zu",romaji:"zu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"で",nl:"de",romaji:"de",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ど",nl:"do",romaji:"do",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ば",nl:"ba",romaji:"ba",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"び",nl:"bi",romaji:"bi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぶ",nl:"bu",romaji:"bu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"べ",nl:"be",romaji:"be",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぼ",nl:"bo",romaji:"bo",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぱ",nl:"pa",romaji:"pa",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぴ",nl:"pi",romaji:"pi",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぷ",nl:"pu",romaji:"pu",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぺ",nl:"pe",romaji:"pe",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぽ",nl:"po",romaji:"po",categorie:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},

  // DAKUTEN KATAKANA
  {jp:"ガ",nl:"ga",romaji:"ga",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ギ",nl:"gi",romaji:"gi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"グ",nl:"gu",romaji:"gu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ゲ",nl:"ge",romaji:"ge",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ゴ",nl:"go",romaji:"go",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ザ",nl:"za",romaji:"za",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ジ",nl:"ji",romaji:"ji",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ズ",nl:"zu",romaji:"zu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ゼ",nl:"ze",romaji:"ze",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ゾ",nl:"zo",romaji:"zo",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ダ",nl:"da",romaji:"da",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ヂ",nl:"ji",romaji:"ji",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ヅ",nl:"zu",romaji:"zu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"デ",nl:"de",romaji:"de",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ド",nl:"do",romaji:"do",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"バ",nl:"ba",romaji:"ba",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ビ",nl:"bi",romaji:"bi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ブ",nl:"bu",romaji:"bu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ベ",nl:"be",romaji:"be",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ボ",nl:"bo",romaji:"bo",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"パ",nl:"pa",romaji:"pa",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ぴ",nl:"pi",romaji:"pi",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"プ",nl:"pu",romaji:"pu",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ペ",nl:"pe",romaji:"pe",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ポ",nl:"po",romaji:"po",categorie:"katakana alfabet",taal:"katakana",hoofdklank:"ha"}
];

export const CATEGORIES = [
  "drinken", "voedsel", "lichaam", "literatuur", "emotie", 
  "school", "cultuur", "natuur", "transport", "kleding", 
  "sport", "groeten", "familie", "tijd", "katakana alfabet", 
  "hiragana alfabet", "overig"
];

export const KANA_ROWS = ["a", "ka", "sa", "ta", "na", "ma", "ha", "wa", "ra", "ya"];
